import { ClassDefinition, TankClass } from '../types/game.ts';

export const TANK_CLASSES: Record<TankClass, ClassDefinition> = {
  // --- TIER 1 ---
  basic: {
    name: 'Basic Tank',
    tier: 1,
    reqLevel: 1,
    description: 'Chiến xa tiêu chuẩn với 1 pháo đơn cân bằng mọi chỉ số.',
    bodyRadius: 24,
    speedMult: 1,
    reloadMult: 1,
    damageMult: 1,
    bodyDamageMult: 1,
    maxHpMult: 1,
    fovMult: 1,
    barrels: [{ angle: 0, offset: 0, width: 18, length: 22, recoil: 4 }],
  },

  // --- TIER 2 (Lv 15) ---
  twin: {
    name: 'Twin',
    tier: 2,
    reqLevel: 15,
    prevClass: ['basic'],
    description: 'Pháo đôi bắn luân phiên với tốc độ áp chế cực cao.',
    bodyRadius: 24,
    speedMult: 1,
    reloadMult: 0.8,
    damageMult: 0.9,
    bodyDamageMult: 1,
    maxHpMult: 1.05,
    fovMult: 1,
    barrels: [
      { angle: 0, offset: -9, width: 14, length: 22, recoil: 3 },
      { angle: 0, offset: 9, width: 14, length: 22, recoil: 3 },
    ],
  },
  sniper: {
    name: 'Sniper',
    tier: 2,
    reqLevel: 15,
    prevClass: ['basic'],
    description: 'Nòng pháo siêu dài, tầm bắn xa vượt trội và đạn cực mạnh.',
    bodyRadius: 24,
    speedMult: 0.95,
    reloadMult: 1.6,
    damageMult: 1.8,
    bodyDamageMult: 1,
    maxHpMult: 1,
    fovMult: 1.25,
    barrels: [
      { angle: 0, offset: 0, width: 17, length: 34, recoil: 8, speedMult: 1.45, damageMult: 1.4 },
    ],
  },
  machine_gun: {
    name: 'Machine Gun',
    tier: 2,
    reqLevel: 15,
    prevClass: ['basic'],
    description: 'Nòng pháo loe bắn liên thanh tốc độ cao với độ giật mạnh.',
    bodyRadius: 24,
    speedMult: 0.98,
    reloadMult: 0.52,
    damageMult: 0.75,
    bodyDamageMult: 1,
    maxHpMult: 1.1,
    fovMult: 1,
    barrels: [
      { angle: 0, offset: 0, width: 23, length: 20, spread: 0.28, recoil: 5 },
    ],
  },
  flank_guard: {
    name: 'Flank Guard',
    tier: 2,
    reqLevel: 15,
    prevClass: ['basic'],
    description: 'Có thêm 1 pháo phía sau bảo vệ mạn sườn và tăng lực đẩy.',
    bodyRadius: 24,
    speedMult: 1.05,
    reloadMult: 0.9,
    damageMult: 0.95,
    bodyDamageMult: 1,
    maxHpMult: 1.05,
    fovMult: 1,
    barrels: [
      { angle: 0, offset: 0, width: 18, length: 22, recoil: 3 },
      { angle: Math.PI, offset: 0, width: 18, length: 17, recoil: 4 },
    ],
  },
  smasher: {
    name: 'Smasher',
    tier: 2,
    reqLevel: 15,
    prevClass: ['basic'],
    description: 'Chiến xa bọc thép gai không súng, chuyên lao húc nghiền nát mục tiêu.',
    bodyRadius: 29,
    speedMult: 1.15,
    reloadMult: 999,
    damageMult: 0,
    bodyDamageMult: 2.5,
    maxHpMult: 1.7,
    fovMult: 1.05,
    isSmasher: true,
    barrels: [],
  },
  overseer: {
    name: 'Overseer',
    tier: 2,
    reqLevel: 15,
    prevClass: ['sniper', 'basic'],
    description: 'Điều khiển đàn Drone tam giác tự hành săn đuổi con mồi.',
    bodyRadius: 24,
    speedMult: 0.98,
    reloadMult: 1.5,
    damageMult: 1.2,
    bodyDamageMult: 1,
    maxHpMult: 1.05,
    fovMult: 1.15,
    isDroneClass: true,
    barrels: [
      { angle: 0, offset: -8, width: 16, length: 21, isDroneSpawner: true },
      { angle: 0, offset: 8, width: 16, length: 21, isDroneSpawner: true },
    ],
  },

  // --- TIER 3 (Lv 30) ---
  triple_shot: {
    name: 'Triple Shot',
    tier: 3,
    reqLevel: 30,
    prevClass: ['twin'],
    description: 'Bắn 3 viên đạn tỏa ra phía trước quét sạch diện tích lớn.',
    bodyRadius: 24,
    speedMult: 1,
    reloadMult: 0.85,
    damageMult: 0.9,
    bodyDamageMult: 1,
    maxHpMult: 1.1,
    fovMult: 1,
    barrels: [
      { angle: -0.45, offset: 0, width: 15, length: 21, recoil: 3 },
      { angle: 0, offset: 0, width: 16, length: 23, recoil: 4 },
      { angle: 0.45, offset: 0, width: 15, length: 21, recoil: 3 },
    ],
  },
  assassin: {
    name: 'Assassin',
    tier: 3,
    reqLevel: 30,
    prevClass: ['sniper'],
    description: 'Tầm nhìn cực rộng, phát hiện mục tiêu và bắn tỉa từ khoảng cách xa.',
    bodyRadius: 24,
    speedMult: 0.92,
    reloadMult: 1.8,
    damageMult: 2.2,
    bodyDamageMult: 1,
    maxHpMult: 1,
    fovMult: 1.45,
    barrels: [
      { angle: 0, offset: 0, width: 17, length: 40, recoil: 10, speedMult: 1.6, damageMult: 1.8 },
    ],
  },
  destroyer: {
    name: 'Destroyer',
    tier: 3,
    reqLevel: 30,
    prevClass: ['machine_gun', 'basic'],
    description: 'Bắn đạn pháo khổng lồ gây sát thương hủy diệt và phản lực cực mạnh.',
    bodyRadius: 26,
    speedMult: 0.9,
    reloadMult: 2.5,
    damageMult: 3.5,
    bodyDamageMult: 1.3,
    maxHpMult: 1.25,
    fovMult: 1.05,
    barrels: [
      { angle: 0, offset: 0, width: 28, length: 24, recoil: 18, bulletScale: 2.0, damageMult: 3.2, speedMult: 0.95 },
    ],
  },
  quad_tank: {
    name: 'Quad Tank',
    tier: 3,
    reqLevel: 30,
    prevClass: ['flank_guard', 'twin'],
    description: 'Bắn 4 hướng hình chữ thập kiểm soát toàn bộ không gian xung quanh.',
    bodyRadius: 24,
    speedMult: 1,
    reloadMult: 0.95,
    damageMult: 0.9,
    bodyDamageMult: 1,
    maxHpMult: 1.15,
    fovMult: 1,
    barrels: [
      { angle: 0, offset: 0, width: 16, length: 21, recoil: 3 },
      { angle: Math.PI / 2, offset: 0, width: 16, length: 21, recoil: 3 },
      { angle: Math.PI, offset: 0, width: 16, length: 21, recoil: 3 },
      { angle: -Math.PI / 2, offset: 0, width: 16, length: 21, recoil: 3 },
    ],
  },
  tri_angle: {
    name: 'Tri-Angle',
    tier: 3,
    reqLevel: 30,
    prevClass: ['flank_guard'],
    description: '2 pháo phụ đẩy lùi phía sau tạo tốc độ phi mã kinh hoàng.',
    bodyRadius: 24,
    speedMult: 1.25,
    reloadMult: 0.75,
    damageMult: 0.85,
    bodyDamageMult: 1.2,
    maxHpMult: 1.15,
    fovMult: 1.05,
    barrels: [
      { angle: 0, offset: 0, width: 17, length: 23, recoil: 3 },
      { angle: (5 * Math.PI) / 6, offset: 0, width: 14, length: 18, recoil: 6 },
      { angle: -(5 * Math.PI) / 6, offset: 0, width: 14, length: 18, recoil: 6 },
    ],
  },
  overlord: {
    name: 'Overlord',
    tier: 3,
    reqLevel: 30,
    prevClass: ['overseer'],
    description: 'Chúa tể Drone với 4 cổng sản xuất và chỉ huy tối đa 8 minion.',
    bodyRadius: 25,
    speedMult: 0.95,
    reloadMult: 1.2,
    damageMult: 1.3,
    bodyDamageMult: 1.1,
    maxHpMult: 1.2,
    fovMult: 1.2,
    isDroneClass: true,
    barrels: [
      { angle: 0, offset: 0, width: 18, length: 22, isDroneSpawner: true },
      { angle: Math.PI / 2, offset: 0, width: 18, length: 22, isDroneSpawner: true },
      { angle: Math.PI, offset: 0, width: 18, length: 22, isDroneSpawner: true },
      { angle: -Math.PI / 2, offset: 0, width: 18, length: 22, isDroneSpawner: true },
    ],
  },
  trapper: {
    name: 'Trapper',
    tier: 3,
    reqLevel: 30,
    prevClass: ['sniper', 'basic'],
    description: 'Phóng ra bẫy gai phòng thủ cố định ngăn đạn và chông gai bảo vệ đồng đội.',
    bodyRadius: 25,
    speedMult: 0.95,
    reloadMult: 1.1,
    damageMult: 1.2,
    bodyDamageMult: 1.2,
    maxHpMult: 1.3,
    fovMult: 1.1,
    barrels: [
      { angle: 0, offset: 0, width: 22, length: 22, isTrapSpawner: true, recoil: 5 },
    ],
  },

  // --- TIER 4 (Lv 45) ---
  triplet: {
    name: 'Triplet',
    tier: 4,
    reqLevel: 45,
    prevClass: ['triple_shot', 'twin'],
    description: '3 nòng pháo song song xả bão đạn tập trung không thể cản phá.',
    bodyRadius: 25,
    speedMult: 1,
    reloadMult: 0.65,
    damageMult: 0.95,
    bodyDamageMult: 1.1,
    maxHpMult: 1.2,
    fovMult: 1,
    barrels: [
      { angle: 0, offset: -10, width: 13, length: 21, recoil: 3 },
      { angle: 0, offset: 10, width: 13, length: 21, recoil: 3 },
      { angle: 0, offset: 0, width: 15, length: 25, recoil: 4 },
    ],
  },
  penta_shot: {
    name: 'Penta Shot',
    tier: 4,
    reqLevel: 45,
    prevClass: ['triple_shot'],
    description: '5 nòng pháo hình quạt bao phủ diện rộng với phản lực lùi cực khỏe.',
    bodyRadius: 25,
    speedMult: 1.05,
    reloadMult: 0.6,
    damageMult: 0.85,
    bodyDamageMult: 1.1,
    maxHpMult: 1.25,
    fovMult: 1.05,
    barrels: [
      { angle: -0.7, offset: 0, width: 13, length: 18, recoil: 3 },
      { angle: 0.7, offset: 0, width: 13, length: 18, recoil: 3 },
      { angle: -0.35, offset: 0, width: 14, length: 22, recoil: 4 },
      { angle: 0.35, offset: 0, width: 14, length: 22, recoil: 4 },
      { angle: 0, offset: 0, width: 16, length: 25, recoil: 5 },
    ],
  },
  annihilator: {
    name: 'Annihilator',
    tier: 4,
    reqLevel: 45,
    prevClass: ['destroyer'],
    description: 'Nòng đại pháo vĩ đại phóng đạn titan thổi bay mọi thứ cản đường.',
    bodyRadius: 27,
    speedMult: 0.88,
    reloadMult: 2.8,
    damageMult: 4.5,
    bodyDamageMult: 1.5,
    maxHpMult: 1.4,
    fovMult: 1.1,
    barrels: [
      { angle: 0, offset: 0, width: 34, length: 26, recoil: 24, bulletScale: 2.6, damageMult: 4.0, speedMult: 1.05 },
    ],
  },
  booster: {
    name: 'Booster',
    tier: 4,
    reqLevel: 45,
    prevClass: ['tri_angle'],
    description: '4 ống phản lực phía sau biến chiếc xe thành tên lửa siêu âm.',
    bodyRadius: 24,
    speedMult: 1.35,
    reloadMult: 0.7,
    damageMult: 0.85,
    bodyDamageMult: 1.6,
    maxHpMult: 1.3,
    fovMult: 1.1,
    barrels: [
      { angle: 0, offset: 0, width: 17, length: 23, recoil: 3 },
      { angle: (5 * Math.PI) / 6, offset: -4, width: 13, length: 18, recoil: 5 },
      { angle: (5 * Math.PI) / 6, offset: 4, width: 13, length: 15, recoil: 5 },
      { angle: -(5 * Math.PI) / 6, offset: -4, width: 13, length: 15, recoil: 5 },
      { angle: -(5 * Math.PI) / 6, offset: 4, width: 13, length: 18, recoil: 5 },
    ],
  },
  fighter: {
    name: 'Fighter',
    tier: 4,
    reqLevel: 45,
    prevClass: ['tri_angle'],
    description: 'Chiến cơ đa nhiệm có 2 pháo cánh bên và 2 phản lực đuôi.',
    bodyRadius: 25,
    speedMult: 1.25,
    reloadMult: 0.7,
    damageMult: 0.95,
    bodyDamageMult: 1.3,
    maxHpMult: 1.3,
    fovMult: 1.1,
    barrels: [
      { angle: 0, offset: 0, width: 17, length: 24, recoil: 3 },
      { angle: Math.PI / 2, offset: 0, width: 14, length: 18, recoil: 3 },
      { angle: -Math.PI / 2, offset: 0, width: 14, length: 18, recoil: 3 },
      { angle: (5 * Math.PI) / 6, offset: 0, width: 13, length: 17, recoil: 5 },
      { angle: -(5 * Math.PI) / 6, offset: 0, width: 13, length: 17, recoil: 5 },
    ],
  },
  hybrid: {
    name: 'Hybrid',
    tier: 4,
    reqLevel: 45,
    prevClass: ['destroyer'],
    description: 'Kết hợp đại bác Destroyer phía trước và tổ Drone tự động phía sau.',
    bodyRadius: 26,
    speedMult: 0.9,
    reloadMult: 2.4,
    damageMult: 3.6,
    bodyDamageMult: 1.3,
    maxHpMult: 1.35,
    fovMult: 1.1,
    isDroneClass: true,
    barrels: [
      { angle: 0, offset: 0, width: 28, length: 25, recoil: 18, bulletScale: 2.0, damageMult: 3.3 },
      { angle: Math.PI, offset: 0, width: 16, length: 18, isDroneSpawner: true },
    ],
  },
  streamliner: {
    name: 'Streamliner',
    tier: 4,
    reqLevel: 45,
    prevClass: ['assassin', 'sniper'],
    description: '5 nòng xếp tầng phóng tia laser đạn liên tục với độ chính xác tuyệt đối.',
    bodyRadius: 24,
    speedMult: 0.95,
    reloadMult: 0.38,
    damageMult: 0.55,
    bodyDamageMult: 1,
    maxHpMult: 1.15,
    fovMult: 1.35,
    barrels: [
      { angle: 0, offset: 0, width: 13, length: 38, speedMult: 1.5, recoil: 1 },
      { angle: 0, offset: 0, width: 14, length: 33, speedMult: 1.5, recoil: 1 },
      { angle: 0, offset: 0, width: 15, length: 28, speedMult: 1.5, recoil: 1 },
      { angle: 0, offset: 0, width: 16, length: 23, speedMult: 1.5, recoil: 1 },
      { angle: 0, offset: 0, width: 17, length: 18, speedMult: 1.5, recoil: 1 },
    ],
  },
  battleship: {
    name: 'Battleship',
    tier: 4,
    reqLevel: 45,
    prevClass: ['overlord', 'twin'],
    description: 'Chiến hạm hạm đội phóng bão Drone mini áp đảo toàn diện.',
    bodyRadius: 25,
    speedMult: 1,
    reloadMult: 0.5,
    damageMult: 0.7,
    bodyDamageMult: 1.1,
    maxHpMult: 1.25,
    fovMult: 1.15,
    isDroneClass: true,
    barrels: [
      { angle: 0, offset: -8, width: 14, length: 18, isDroneSpawner: true },
      { angle: 0, offset: 8, width: 14, length: 18, isDroneSpawner: true },
      { angle: Math.PI, offset: -8, width: 14, length: 18, isDroneSpawner: true },
      { angle: Math.PI, offset: 8, width: 14, length: 18, isDroneSpawner: true },
    ],
  },
};

export const AVAILABLE_CLASSES_BY_TIER: Record<number, TankClass[]> = {
  1: ['basic'],
  2: ['twin', 'sniper', 'machine_gun', 'flank_guard', 'smasher', 'overseer'],
  3: ['triple_shot', 'assassin', 'destroyer', 'quad_tank', 'tri_angle', 'overlord', 'trapper'],
  4: ['triplet', 'penta_shot', 'annihilator', 'booster', 'fighter', 'hybrid', 'streamliner', 'battleship'],
};

export function getAvailableUpgrades(currentClass: TankClass, level: number): TankClass[] {
  if (level < 15) return [];

  if (level >= 45) {
    // Tier 4
    return AVAILABLE_CLASSES_BY_TIER[4].filter((cls) => {
      const def = TANK_CLASSES[cls];
      if (!def.prevClass) return true;
      return def.prevClass.includes(currentClass) || currentClass === 'basic';
    });
  }

  if (level >= 30) {
    // Tier 3
    return AVAILABLE_CLASSES_BY_TIER[3].filter((cls) => {
      const def = TANK_CLASSES[cls];
      if (!def.prevClass) return true;
      return def.prevClass.includes(currentClass) || currentClass === 'basic';
    });
  }

  if (level >= 15 && currentClass === 'basic') {
    // Tier 2
    return AVAILABLE_CLASSES_BY_TIER[2];
  }

  return [];
}
